name: First Workflow
on: workflow_dispatch

#This is a Comment
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "Testing multi line command "
      - name: Print goodbye
        run: echo "Done - Goodbye"
